# Generated by Django 4.1.2 on 2022-11-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_info_section_socialmedia_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='FieldTechnology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.technologyfield')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.technology')),
            ],
        ),
    ]
