# Generated by Django 4.1.2 on 2022-11-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_technologyfield_info_value_socialmedia_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnologyField',
            new_name='Field',
        ),
    ]
