name: Build and Deploy Container to DigitalOcean

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python manage.py test
    
    - name: Build Container Image
      run: docker build . --file Dockerfile --tag ghcr.io/aymaneboukrouh/aymaneboukrouh:latest
      
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Push Image to GitHub Container Registry
      run: docker push ghcr.io/aymaneboukrouh/aymaneboukrouh:latest
      
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v2
      with:
        host: aymaneboukrouh.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Log into GitHub Container Registry on DigitalOcean
      run: ssh root@aymaneboukrouh.com 'echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin'
      
    - name: Pull Container Image
      run: ssh root@aymaneboukrouh.com 'docker pull ghcr.io/aymaneboukrouh/aymaneboukrouh:latest'
      
    - name: Run Container Image
      run: ssh root@aymaneboukrouh.com 'docker-compose -f /home/aymane/docker-compose.yml up --build -d'
      
